{
 "title": "Jobber Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"jobber\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Jobber Down Alert", "type": "alertlist", "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 } },
  {
   "title": "Scheduled Queries",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(jobber_schedulded_queries)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New Queries",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jobber_new_queries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=\"jobber\"} |= `ERROR`"
    }
   ]
  }
 ]
}