// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Offer struct {
	ID        string
	Title     string
	Company   string
	Location  string
	PostedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Query struct {
	ID        int64
	Keywords  string
	Location  string
	CreatedAt pgtype.Timestamptz
	QueriedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type QueryOffer struct {
	QueryID int64
	OfferID string
}
