// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOffer = `-- name: CreateOffer :exec
INSERT INTO offers (id, title, company, location, posted_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO NOTHING
`

type CreateOfferParams struct {
	ID       string
	Title    string
	Company  string
	Location string
	PostedAt pgtype.Timestamptz
}

func (q *Queries) CreateOffer(ctx context.Context, arg *CreateOfferParams) error {
	_, err := q.db.Exec(ctx, createOffer,
		arg.ID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.PostedAt,
	)
	return err
}

const createQuery = `-- name: CreateQuery :one
INSERT INTO
    queries (keywords, location)
VALUES
    ($1, $2) RETURNING id, keywords, location, created_at, queried_at, updated_at
`

type CreateQueryParams struct {
	Keywords string
	Location string
}

func (q *Queries) CreateQuery(ctx context.Context, arg *CreateQueryParams) (*Query, error) {
	row := q.db.QueryRow(ctx, createQuery, arg.Keywords, arg.Location)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.Location,
		&i.CreatedAt,
		&i.QueriedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createQueryOfferAssoc = `-- name: CreateQueryOfferAssoc :exec
INSERT INTO query_offers (query_id, offer_id)
VALUES ($1, $2)
ON CONFLICT (query_id, offer_id) DO NOTHING
`

type CreateQueryOfferAssocParams struct {
	QueryID int64
	OfferID string
}

func (q *Queries) CreateQueryOfferAssoc(ctx context.Context, arg *CreateQueryOfferAssocParams) error {
	_, err := q.db.Exec(ctx, createQueryOfferAssoc, arg.QueryID, arg.OfferID)
	return err
}

const deleteQuery = `-- name: DeleteQuery :exec
DELETE FROM queries
WHERE
    id = $1
`

func (q *Queries) DeleteQuery(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteQuery, id)
	return err
}

const getQuery = `-- name: GetQuery :one
SELECT
    id, keywords, location, created_at, queried_at, updated_at
FROM
    queries
WHERE
    keywords = $1
    AND location = $2
`

type GetQueryParams struct {
	Keywords string
	Location string
}

func (q *Queries) GetQuery(ctx context.Context, arg *GetQueryParams) (*Query, error) {
	row := q.db.QueryRow(ctx, getQuery, arg.Keywords, arg.Location)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.Location,
		&i.CreatedAt,
		&i.QueriedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getQueryByID = `-- name: GetQueryByID :one
SELECT
    id, keywords, location, created_at, queried_at, updated_at
FROM
    queries
WHERE
    id = $1
`

func (q *Queries) GetQueryByID(ctx context.Context, id int64) (*Query, error) {
	row := q.db.QueryRow(ctx, getQueryByID, id)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.Location,
		&i.CreatedAt,
		&i.QueriedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listOffers = `-- name: ListOffers :many
SELECT
    o.id, o.title, o.company, o.location, o.posted_at, o.created_at
FROM
    queries q
    JOIN query_offers qo ON q.id = qo.query_id
    JOIN offers o ON qo.offer_id = o.id
WHERE
    q.id = $1
    AND o.posted_at >= $2
ORDER BY
    o.posted_at DESC
`

type ListOffersParams struct {
	ID       int64
	PostedAt pgtype.Timestamptz
}

func (q *Queries) ListOffers(ctx context.Context, arg *ListOffersParams) ([]*Offer, error) {
	rows, err := q.db.Query(ctx, listOffers, arg.ID, arg.PostedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.PostedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueries = `-- name: ListQueries :many
SELECT
    id, keywords, location, created_at, queried_at, updated_at
FROM
    queries
`

func (q *Queries) ListQueries(ctx context.Context) ([]*Query, error) {
	rows, err := q.db.Query(ctx, listQueries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Query
	for rows.Next() {
		var i Query
		if err := rows.Scan(
			&i.ID,
			&i.Keywords,
			&i.Location,
			&i.CreatedAt,
			&i.QueriedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQueryQAT = `-- name: UpdateQueryQAT :exec
UPDATE queries
SET
    queried_at = CURRENT_TIMESTAMP
WHERE
    id = $1
`

func (q *Queries) UpdateQueryQAT(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateQueryQAT, id)
	return err
}

const updateQueryUAT = `-- name: UpdateQueryUAT :exec
UPDATE queries
SET
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
`

func (q *Queries) UpdateQueryUAT(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateQueryUAT, id)
	return err
}
