// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const createOffer = `-- name: CreateOffer :exec
INSERT INTO
    offers (id, title, company, location, posted_at, query_id)
VALUES
    (?, ?, ?, ?, ?, ?)
`

type CreateOfferParams struct {
	ID       string
	Title    string
	Company  string
	Location string
	PostedAt time.Time
	QueryID  int64
}

func (q *Queries) CreateOffer(ctx context.Context, arg *CreateOfferParams) error {
	_, err := q.db.ExecContext(ctx, createOffer,
		arg.ID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.PostedAt,
		arg.QueryID,
	)
	return err
}

const createQuery = `-- name: CreateQuery :one
INSERT INTO
    queries (keywords, location, f_tpr, f_jt)
VALUES
    (?, ?, ?, ?) RETURNING id, keywords, location, f_tpr, f_jt, created_at
`

type CreateQueryParams struct {
	Keywords string
	Location string
	FTpr     string
	FJt      string
}

func (q *Queries) CreateQuery(ctx context.Context, arg *CreateQueryParams) (*Query, error) {
	row := q.db.QueryRowContext(ctx, createQuery,
		arg.Keywords,
		arg.Location,
		arg.FTpr,
		arg.FJt,
	)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.Location,
		&i.FTpr,
		&i.FJt,
		&i.CreatedAt,
	)
	return &i, err
}

const listOffers = `-- name: ListOffers :many
SELECT
    id, query_id, title, company, location, ignored, posted_at, created_at
FROM
    offers
WHERE
    query_id = ?
    AND ignored = 0
ORDER BY
    posted_at DESC
`

func (q *Queries) ListOffers(ctx context.Context, queryID int64) ([]*Offer, error) {
	rows, err := q.db.QueryContext(ctx, listOffers, queryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.QueryID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Ignored,
			&i.PostedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueries = `-- name: ListQueries :many
SELECT
    id, keywords, location, f_tpr, f_jt, created_at
FROM
    queries
`

func (q *Queries) ListQueries(ctx context.Context) ([]*Query, error) {
	rows, err := q.db.QueryContext(ctx, listQueries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Query
	for rows.Next() {
		var i Query
		if err := rows.Scan(
			&i.ID,
			&i.Keywords,
			&i.Location,
			&i.FTpr,
			&i.FJt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
